### INVERTER ###
ENV_INVERTER_HOST = 'SUNGATHER_INVERTER_HOST'
ENV_INVERTER_PORT = 'SUNGATHER_INVERTER_PORT'
ENV_INVERTER_SLAVE = 'SUNGATHER_INVERTER_SLAVE'
ENV_INVERTER_MODEL = 'SUNGATHER_INVERTER_MODEL'
ENV_INVERTER_SMART_METER = 'SUNGATHER_INVERTER_SMART_METER'
ENV_INVERTER_USE_LOCAL_TIME = 'SUNGATHER_INVERTER_USE_LOCAL_TIME'

### CLIENT ####
ENV_CLIENT_RETRIES = 'SUNGATHER_RETRIES'
ENV_CLIENT_TIMEOUT = 'SUNGATHER_TIMEOUT'
ENV_CLIENT_SCAN_INTERVAL = 'SUNGATHER_SCAN_INTERVAL'
ENV_CLIENT_CONNECTION = 'SUNGATHER_CONNECTION'
ENV_CLIENT_LOG_CONSOLE = 'SUNGATHER_LOG_CONSOLE_LEVEL'
ENV_CLIENT_LOG_FILE = 'SUNGATHER_LOG_FILE_LEVEL'
ENV_CLIENT_SCAN_LEVEL = 'SUNGATHER_SCAN_LEVEL'

## EXPORTS ##
### CONSOLE ###
ENV_CONSOLE = 'SUNGATHER_EXPORT_CONSOLE'

### WEBSERVER ###
ENV_WEBSERVER = 'SUNGATHER_EXPORT_WEBSERVER'
ENV_WEBSERVER_PORT = 'SUNGATHER_WEBSERVER_PORT'

### JSONSERVER ###
ENV_JSONSERVER = 'SUNGATHER_EXPORT_JSONSERVER'
ENV_JSONSERVER_PORT = 'SUNGATHER_JSONSERVER_PORT'

### INFLUX DB ###
ENV_INFLUX = 'SUNGATHER_EXPORT_INFLUX'
ENV_INFLUX_URL = 'SUNGATHER_INFLUX_URL'
ENV_INFLUX_TOKEN = 'SUNGATHER_INFLUX_TOKEN'
ENV_INFLUX_USERNAME = 'SUNGATHER_INFLUX_USER'
ENV_INFLUX_PASSWORD = 'SUNGATHER_INFLUX_PASSWORD'
ENV_INFLUX_ORG = 'SUNGATHER_INFLUX_ORG'
ENV_INFLUX_BUCKET = 'SUNGATHER_INFLUX_BUCKET'

### MQTT ###
ENV_MQTT = 'SUNGATHER_EXPORT_MQTT'
ENV_MQTT_HOST = 'SUNGATHER_MQTT_HOST'
ENV_MQTT_PORT = 'SUNGATHER_MQTT_PORT'
ENV_MQTT_CLIENTID = 'SUNGATHER_MQTT_CLIENTID'
ENV_MQTT_TOPIC = 'SUNGATHER_MQTT_TOPIC'
ENV_MQTT_USERNAME = 'SUNGATHER_MQTT_USERNAME'
ENV_MQTT_PASSWORD = 'SUNGATHER_MQTT_PASSWORD'
ENV_MQTT_HA = 'SUNGATHER_MQTT_HOMEASSISTANT'

### PVOUTPUT ###
ENV_PVOUTPUT = 'SUNGATHER_EXPORT_PVOUTPUT'
ENV_PVOUTPUT_API = 'SUNGATHER_PVOUTPUT_API'
ENV_PVOUTPUT_SID = 'SUNGATHER_PVOUTPUT_SID'
ENV_PVOUTPUT_JOIN_TEAM = 'SUNGATHER_PVOUTPUT_JOIN_TEAM'
ENV_PVOUTPUT_RATE_LIMIT = 'SUNGATHER_PVOUTPUT_RATE_LIMIT'
ENV_PVOUTPUT_CUMULATIVE_FLAG = 'SUNGATHER_PVOUTPUT_CUMULATIVE_FLAG'
ENV_PVOUTPUT_BATCH_POINTS = 'SUNGATHER_PVOUTPUT_PATCH_POINTS'
