### INFLUX DB ###
ENV_INFLUX = 'SUNGATHER_INFLUX_PUBLISH'
ENV_INFLUX_URL = 'SUNGATHER_INFLUX_URL'
ENV_INFLUX_TOKEN = 'SUNGATHER_INFLUX_TOKEN'
ENV_INFLUX_USERNAME = 'SUNGATHER_INFLUX_USER'
ENV_INFLUX_PASSWORD = 'SUNGATHER_INFLUX_PASSWORD'
ENV_INFLUX_ORG = 'SUNGATHER_INFLUX_ORG'
ENV_INFLUX_BUCKET = 'SUNGATHER_INFLUX_BUCKET'
