### INVERTER ###
# ToDo

## EXPORTS ##
### WEBSERVER ###
ENV_WEBSERVER = 'SUNGATHER_WEBSERVER_PUBLISH'
ENV_WEBSERVER_PORT = 'SUNGATHER_WEBSERVER_PORT'

### JSONSERVER ###
ENV_JSONSERVER = 'SUNGATHER_JSONSERVER_PUBLISH'
ENV_JSONSERVER_PORT = 'SUNGATHER_JSONSERVER_PORT'

### INFLUX DB ###
ENV_INFLUX = 'SUNGATHER_INFLUX_PUBLISH'
ENV_INFLUX_URL = 'SUNGATHER_INFLUX_URL'
ENV_INFLUX_TOKEN = 'SUNGATHER_INFLUX_TOKEN'
ENV_INFLUX_USERNAME = 'SUNGATHER_INFLUX_USER'
ENV_INFLUX_PASSWORD = 'SUNGATHER_INFLUX_PASSWORD'
ENV_INFLUX_ORG = 'SUNGATHER_INFLUX_ORG'
ENV_INFLUX_BUCKET = 'SUNGATHER_INFLUX_BUCKET'

### MQTT ###
ENV_MQTT = 'SUNGATHER_MQTT_PUBLISH'
ENV_MQTT_HOST = 'SUNGATHER_MQTT_HOST'
ENV_MQTT_PORT = 'SUNGATHER_MQTT_PORT'
ENV_MQTT_CLIENTID = 'SUNGATHER_MQTT_CLIENTID'
ENV_MQTT_TOPIC = 'SUNGATHER_MQTT_TOPIC'
ENV_MQTT_USERNAME = 'SUNGATHER_MQTT_USERNAME'
ENV_MQTT_PASSWORD = 'SUNGATHER_MQTT_PASSWORD'
ENV_MQTT_HA = 'SUNGATHER_MQTT_HOMEASSISTANT'

### PVOUTPUT ###
ENV_PVOUTPUT = 'SUNGATHER_PVOUTPUT_PUBLISH'
ENV_PVOUTPUT_API = 'SUNGATHER_PVOUTPUT_API'
ENV_PVOUTPUT_SID = 'SUNGATHER_PVOUTPUT_SID'
ENV_PVOUTPUT_JOIN_TEAM = 'SUNGATHER_PVOUTPUT_JOIN_TEAM'
ENV_PVOUTPUT_RATE_LIMIT = 'SUNGATHER_PVOUTPUT_RATE_LIMIT'
ENV_PVOUTPUT_CUMULATIVE_FLAG = 'SUNGATHER_PVOUTPUT_CUMULATIVE_FLAG'
ENV_PVOUTPUT_BATCH_POINTS = 'SUNGATHER_PVOUTPUT_PATCH_POINTS'
